 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/budgets_groups", type: :request do
  # BudgetsGroup. As you add validations to BudgetsGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BudgetsGroup.create! valid_attributes
      get budgets_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      budgets_group = BudgetsGroup.create! valid_attributes
      get budgets_group_url(budgets_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_budgets_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      budgets_group = BudgetsGroup.create! valid_attributes
      get edit_budgets_group_url(budgets_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BudgetsGroup" do
        expect {
          post budgets_groups_url, params: { budgets_group: valid_attributes }
        }.to change(BudgetsGroup, :count).by(1)
      end

      it "redirects to the created budgets_group" do
        post budgets_groups_url, params: { budgets_group: valid_attributes }
        expect(response).to redirect_to(budgets_group_url(BudgetsGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BudgetsGroup" do
        expect {
          post budgets_groups_url, params: { budgets_group: invalid_attributes }
        }.to change(BudgetsGroup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post budgets_groups_url, params: { budgets_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested budgets_group" do
        budgets_group = BudgetsGroup.create! valid_attributes
        patch budgets_group_url(budgets_group), params: { budgets_group: new_attributes }
        budgets_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the budgets_group" do
        budgets_group = BudgetsGroup.create! valid_attributes
        patch budgets_group_url(budgets_group), params: { budgets_group: new_attributes }
        budgets_group.reload
        expect(response).to redirect_to(budgets_group_url(budgets_group))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        budgets_group = BudgetsGroup.create! valid_attributes
        patch budgets_group_url(budgets_group), params: { budgets_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested budgets_group" do
      budgets_group = BudgetsGroup.create! valid_attributes
      expect {
        delete budgets_group_url(budgets_group)
      }.to change(BudgetsGroup, :count).by(-1)
    end

    it "redirects to the budgets_groups list" do
      budgets_group = BudgetsGroup.create! valid_attributes
      delete budgets_group_url(budgets_group)
      expect(response).to redirect_to(budgets_groups_url)
    end
  end
end
